import { Separator } from "@/components/ui/separator";
import { IoMailSharp } from "react-icons/io5";
import { FaPhoneAlt } from "react-icons/fa";
import { FaLocationDot } from "react-icons/fa6";
import {
  SlSocialFacebook,
  SlSocialInstagram,
  SlSocialLinkedin,
} from "react-icons/sl";
import Link from "next/link";
import { Metadata } from "next";
import ContactForm from "@/components/UiComponents/ContactForm";

export const metadata: Metadata = {
  title: "contact-us",
  description: "Generated by Abenu",
};

function page() {
  const ContactCard = ({
    id,
    label,
    link,
  }: {
    id: number;
    label: string;
    link: string;
  }) => {
    return (
      <div className="flex gap-4 items-center">
        <span className="h-10 w-10 border flex items-center justify-center rounded-full border-black">
          {id === 1 ? (
            <IoMailSharp className="scale-125" />
          ) : id === 2 ? (
            <FaPhoneAlt />
          ) : (
            <FaLocationDot />
          )}
        </span>
        <span className="flex flex-col">
          <b className="capitalize">{label}</b>
          <small className="font-serif">{link}</small>
        </span>
      </div>
    );
  };
  return (
    <div className="flex gap-2 max-w-[1200px] max-md:flex-col mx-auto w-full px-5 my-10 min-h-screen">
      <div className="flex flex-col gap-4 items-center md:w-[40%] h-full">
        <h1 className="font-bold text-start w-full text-4xl font-serif">
          Let{"'"}s Talk
        </h1>
        <p className="text-sm text-start w-full">
          We collaborate with thousands of creators, entrepreneurs and complete
          legends.
        </p>
        <Separator />
        <div className="flex flex-col gap-5 w-full">
          <ContactCard
            id={1}
            label="our email"
            link="abenuberhanu271@gmail.com"
          />
          <ContactCard id={2} label="call us" link="+251954704213" />
          <ContactCard id={3} label="find us" link="Open Google Maps" />
        </div>
        <Separator />
        <div className="flex gap-4 w-fit p-2 mr-auto items-center justify-center">
          <Link href={"https://www.facebook.com/profile.php?id=61551702750724"}>
            <SlSocialFacebook />
          </Link>
          <Link href={"https://www.instagram.com/abenu855/"}>
            <SlSocialInstagram />
          </Link>
          <Link href={"www.linkedin.com/in/abenezer-berhanu"}>
            <SlSocialLinkedin />
          </Link>
        </div>
      </div>
      <div className="border md:w-[60%] p-3 bg-gray_white rounded-md h-fit">
        <ContactForm />
      </div>
    </div>
  );
}

export default page;
